### ISSUE TITLE
UCLA PTSD section get cut off in IE

### ISSUE THREAD

**Issue by iandd0824** [iandd0824/bhi_m2#3]
The PTSD RI section gets cut off in IE because of the style `overflow: hidden` in [rubick.css](https://github.com/iandd0824/bhi_m2/blob/master/html/app/design/frontend/BHI/Djanny/web/css/rubick.css#L4177-L4179)

```CSS
.section-we-made-1 {
    overflow: hidden;
}
```

![image](https://cloud.githubusercontent.com/assets/1960924/24419300/894e2e0a-13a3-11e7-956d-8c8af6527560.png)

**Comment by iandd0824** [comment]
[/html/app/design/frontend/BHI/Djanny/web/css/rubick.css](https://github.com/iandd0824/bhi_m2/commit/a82801d50fbc822ee6df7be19cc90fd3d7b8ee62#diff-c52d2d9bce2975970cb97ff53e04245b)

Add a82801d50fbc822ee6df7be19cc90fd3d7b8ee62
```CSS
@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {  
   .section-we-made-1 {
      overflow: visible;
   }
}
```
Remove f5f2a4a4fdd13037a88e67ab0ef77bb206be754a
```CSS
.footer {
  overflow: hidden;
}
```
